[project]
name = "climate-pinn"
version = "0.1.0"
description = "Climate pinn project"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "contourpy>=1.3.3",
    "matplotlib>=3.10.7",
    "torch>=2.9.1",
]
